### ISSUE TITLE
实现中英文文档

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/Bizard#95]
- https://docs.ropensci.org/babelquarto/index.html

**Comment by ShixiangWang** [comment]
@Wangcy-rachel

**Comment by Wangcy-rachel** [comment]
经过几天的实践，实现中英文切换可能是按照以下流程：

1.首先是生成单个qmd文档的中文/英文版本：

需要使用到babeldown包，并且要有deepl的API密匙。

**安装包**

```R
install.packages('babeldown', 
                 repos = c('https://ropensci.r-universe.dev', 
                           'https://cloud.r-project.org'))
library(babeldown)

## 或者
# install.packages("pak")
pak::pak("ropensci-review-tools/babeldown")
library(babeldown)

```

**转换qmd文档**

```R
Sys.setenv(DEEPL_API_URL = "https://api.deepl-pro.com") 
Sys.setenv(DEEPL_API_KEY = "6c400dbf-7923-41ba-94b2-d5fa5c1b55a7:dp")
deepl_translate_quarto(
  book_path = "C:/Users/wangchy/Desktop/trail/trail2/trail",
  chapter = "regression_table.qmd",
  source_lang = "ZH",
  target_lang = "EN-US"
)
```

注：需要在Sys.setenv设置好deepl的网址和api。`book_path`是设置路径，`chapter`具体到某个qmd文档，`source_lang`是原qmd文档，target_lang是要翻译的目标语言。这里是将”ZH”（中文）翻译成“EN-US”英文。。

**翻译效果**

原qmd文档：

![Image](https://github.com/user-attachments/assets/1aa3cd3c-fea1-4b8a-ba87-5c4506652922)

翻译后的qmd文档：

![Image](https://github.com/user-attachments/assets/e21393db-8af1-4a8e-92a9-7f15b271ff1a)

注：能够实现翻译功能，不过可能需要人工校验下，而且**代码框中如果有中文注释的话，不会进行翻译**。

2.之后的工作就是创建网页项目，得到可以实现中英文切换的网站。

这里主要用到babelquatro包。

**安装包**

```R
install.packages('babelquarto', 
                 repos = c('https://ropensci.r-universe.dev', 
                           'https://cloud.r-project.org'))
library(babelquarto)

## 或者
# install.packages("pak")
pak::pak("ropensci-review-tools/babelquarto")
library(babelquarto)
```

**创建多语言网页项目**

```R
parent_dir <- "C:/Users/wangchy/Desktop/babel/babel_main"
project_dir <- "babel_multi"
babelquarto::quarto_multilingual_website(
  parent_dir = parent_dir,
  project_dir = project_dir,
  main_language = "en",
  further_languages = "zh"
)
```

注：使用quarto_multilingual_website函数创建多语言切换的网站项目。其中`parent_dir`是你当前的单语言网页项目，得到的多语言文件项目会保存到`project_dir`

需要注意的是，使用这个函数创建后，新的文件夹中会多出你原来的qmd文件的zh.qmd版本，如图：

![Image](https://github.com/user-attachments/assets/fd5c8d21-92cb-4941-b824-0c82d2290fcb)

但是这个中文qmd文件并没有翻译效果，只是原qmd文件的副本，这里就需要**使用你在第一步翻译得到的qmd文件去替换这些副本**。

**配置yml文件**

配置的yml文件要类似于这个格式

```yml
project:
  type: website

website:
  site-url: https://example.com
  title: "multilingual_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: en
    text: "Version in en"
  - name: zh
    text: "Version in zh"
  mainlanguage: 'en'
  languages: ['zh']
title-zh: title in zh
description-zh: description in zh
author-zh: author in zh
lang: en
```

注：这里描述一下其中的参数意思。

`site-url`是网页部署的网址，如果在本地进行测试时，直接把这行删掉。`title`是网站的名称，`title`下面几行时网页中qmd文档的布局，`format`这几行一般不用改。`babelquarto`这一部分是对babelquarto的设置，其中`languagelinks`是中英文切换的标志，`languagecodes`是中英文切换按钮显示的文本，`mainlanguage`,`languages`分别是目前显示的语言和可以切换的语言。`title-zh`,`description-zh`,`author-zh`分别设置的是中文版本网站的标题、描述、作者。

**实现多语言项目**

配置好yml文件后，将qmd文件进行`render`操作，并且输出为网页形式：

```R
babelquarto::render_website(file.path(parent_dir, project_dir))

# For a multilingual website
servr::httw("_site")
```

最终会出现一个中英文切换的标识：

![Image](https://github.com/user-attachments/assets/929a20b7-ba87-43f3-bb41-c5d2ed474b7e)

zh版本的网址差不多是在原网址的基础上加上/zh/。

3.如果还有什么不懂的，可以参考原官方文档，多进行测试。

- babelquatro:[[Get started • babelquarto](https://docs.ropensci.org/babelquarto/articles/babelquarto.html)](https://docs.ropensci.org/babelquarto/articles/babelquarto.html)

- babeldown:https://docs.ropensci.org/babeldown

**Comment by Wangcy-rachel** [comment]
@ZhengTiger  王诗翔老师让您推进实施下这个中英文切换

**Comment by ZhengTiger** [comment]
好的，我试下看看

**Comment by ShixiangWang** [comment]
@ZhengTiger 你先 fork 仓库本地测试，看看怎么把网站 reshape 下更改为同时支持中英文教程切换，完成后微信和我说下，后面再通过 pr 提交

**Comment by ZhengTiger** [comment]
## 中英文双语网站的实现和运维

> 使用 [babelquarto](https://github.com/ropensci-review-tools/babelquarto) 实现，测试效果链接：<https://zhengtiger.github.io/Bizard/>


**安装 babelquarto**

```R
install.packages('babelquarto', repos = c('https://ropensci.r-universe.dev', 'https://cloud.r-project.org'))
```

**在 Bizard 原有项目的基础上增加双语功能**

打开 Bizard 项目 R project，运行以下代码：

```R
project_path <- "."

babelquarto::register_main_language(
  main_language = "en",
  project_path = project_path
)

babelquarto::register_further_languages(
  further_languages = "zh",
  project_path = project_path
)
```

注：`register_main_language` 函数为项目设置主语言，这里为英文 `en`，`register_further_languages` 函数为项目设置副语言，这里为中文 `zh`，`project_path` 为 Bizard 项目路径。

运行完上面的代码后，会在项目的 `_quarto.yml` 配置文件底部自动添加几行新的代码：

```yml
babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: zh
    text: "中文"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['zh']
title-es: "English"
title-zh: "中文"
lang: en
```

这里参数我已经按照项目要求进行了配置，`languagelinks` 用于设置语言按钮的位置，Bizard 项目中应放到 sidebar；`languagecodes` 用于设置语言切换按钮显示的文本；`mainlanguage` 和 `languages` 用于设置可以切换的语言。`title-es` 和 `title-es` 用于设置网站的中英文标题；`lang` 为网站的主语言。

注：关于 `_quarto.yml` 配置文件中的目录章节不用另外修改，按照原项目只设置英文版的 `.qmd` 文件即可，`babelquarto` 会自动按照英文版的目录设置给中文版分配目录。

配置完成后还需要添加相应语言的文件，英文版本文件直接以 `.qmd` 结尾，中文版本文件以 `.zh.qmd` 文件结尾，如下所示：

![Image](https://github.com/user-attachments/assets/69165fef-6668-4fca-aed1-456e6c59678b)

之后按照文档格式要求分别撰写英文版和中文版 `qmd` 文件：

![Image](https://github.com/user-attachments/assets/9cb2c87c-9e1e-447b-9a15-f9b87b4cb72d)

**网站渲染**

这里需要注意，网站渲染必须使用 `babelquarto` 的 `render_website` 函数渲染，如果使用 Rstudio 的 `Render Website` 按钮无法渲染出 babelquarto 的双语言功能。

渲染和预览网站代码如下：

```R
babelquarto::render_website(project_path)
servr::httw("./_site/")
```

渲染完成后在如下红色方框位置多了语言选择按钮，可以切换中英文

![Image](https://github.com/user-attachments/assets/72fc7a46-9c06-41fb-bd06-6ac83464c08e)
